// Generated by '@import-meta-env/typescript'

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

interface ImportMetaEnv {
  readonly NEXT_PUBLIC_API_URL: string;
  readonly NEXT_PUBLIC_SENTRY_PERF_TRACES_SAMPLE_RATE: string;
  readonly NEXT_PUBLIC_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE: string;
  readonly NEXT_PUBLIC_SENTRY_REPLAY_SAMPLE_RATE: string;
  readonly SENTRY_DSN: string;
  readonly SENTRY_ENV: string;
  readonly SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE: string;
}
