// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly NEXT_PUBLIC_VERBOSE: string;
  readonly NEXT_PUBLIC_REMOTE_API_URL: string;
  readonly NEXT_PUBLIC_DOMAIN: string;
  readonly NEXT_PUBLIC_COOKIE_DOMAIN: string;
  readonly NEXT_PUBLIC_LANDING_URL: string;
  readonly NEXT_PUBLIC_AB_DEBUG_ENABLED: string;
  readonly NEXT_PUBLIC_DADATA_TOKEN: string;
  readonly NEXT_PUBLIC_RECAPTCHA_KEY: string;
  readonly NEXT_PUBLIC_RECAPTCHA_ENABLED: string;
  readonly NEXT_PUBLIC_CLICKHOUSE_URL_V2: string;
  readonly NEXT_PUBLIC_CLICKHOUSE_CLIENT_ID: string;
  readonly NEXT_PUBLIC_CLICKHOUSE_TOKEN: string;
  readonly NEXT_PUBLIC_CLICKHOUSE_DRY: string;
  readonly NEXT_PUBLIC_TIDA_HOST: string;
  readonly NEXT_PUBLIC_TIDA_TOKEN: string;
  readonly NEXT_PUBLIC_ESIDA_HOST: string;
  readonly NEXT_PUBLIC_ESIDA_TOKEN: string;
  readonly SENTRY_PERF_TRACES_SAMPLE_RATE: string;
  readonly SENTRY_ENV: string;
  readonly SENTRY_DSN: string;
  readonly SENTRY_REPLAY_SAMPLE_RATE: string;
  readonly SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
