/**
 * Tailwind Theme
 *
 * First, add the new values to the appropriate category in the theme file.
 * Then, run [pnpm run update-theme] to apply the changes.
 * If adding a new category, modify the update script accordingly.
 */

import fs from 'node:fs';
import path from 'node:path';

import jsonTokens from './tokens.json' with { type: 'json' };

function buildTailwindTheme(tokens: typeof jsonTokens) {
  const warning =
    '/* ⚠️ AUTO-GENERATED by src/styles/theme/update-tw-theme.mts. Do not modify directly. */';

  return `${warning}\n\n@theme {
  /* Wildcards */
  --text-*: initial;
  --radius-*: initial;
  --spacing-*: initial;
  --color-*: initial;
  --font-weight-*: initial;
  --font-*: initial;
  --leading-*: initial;
  --shadow-*: initial;
  --inset-shadow-*: initial;
  --drop-shadow-*: initial;
  --breakpoint-*: initial;
  --tracking-*: initial;
  --blur-*: initial;
  --perspective-*: initial;
  --aspect-*: initial;
  --ease-*: initial;
  --animate-*: initial;

  /* Colors */
  ${Object.entries(tokens.color)
    .map(([k, v]) => `  --color-${k}: ${v};`)
    .join('\n')}

  /* Spacing */
  ${Object.entries(tokens.spacing)
    .map(([k, v]) => `  --spacing-${k}: ${v};`)
    .join('\n')}

  /* Radius */
  ${Object.entries(tokens.radius)
    .map(([k, v]) => `  --radius-${k}: ${v};`)
    .join('\n')}

  /* Breakpoints */
  ${Object.entries(tokens.breakpoint)
    .map(([k, v]) => `  --breakpoint-${k}: ${v};`)
    .join('\n')}

  /* Fonts */
  --font-display: ${tokens.typography.fontFamily};

  ${Object.entries(tokens.typography.fontSize)
    .map(([k, v]) => `  --text-${k}: ${v};`)
    .join('\n')}

  ${Object.entries(tokens.typography.fontWeight)
    .map(([k, v]) => `  --font-weight-${k}: ${v};`)
    .join('\n')}

  ${Object.entries(tokens.typography.lineHeight)
    .map(([k, v]) => `  --leading-${k}: ${v};`)
    .join('\n')}
}`.replaceAll(' '.repeat(4), '\t');
}

// ---------- Write files ----------
const twOut = path.resolve('src/styles/theme/tw-theme.css');

fs.writeFileSync(twOut, buildTailwindTheme(jsonTokens), 'utf8');
